"""Demo 7 — The latent graph: connecting vectors so they are easier to traverse.

Question under investigation (repository owner, 2026-08): can we create a
graph from vectors — connect them in a way that makes them easier to
traverse, and does an ontology fall out?

Position tested: the graph is ALREADY LATENT in an embedding band. Nodes are
given; everything else is geometry — and the honest headline of this demo is
that the geometry must be MEASURED before choosing traversal laws:

  7a  edges + navigation: kNN links + a few random long-range links make the
      band navigable — but the load-bearing ingredient is edge SYMMETRY:
      a directed kNN graph strands nodes nobody points at, and greedy
      routing on it fails a third of the time; make the links bidirectional
      (as HNSW does) and even greedy succeeds, while best-first search with
      backtracking (the algorithm inside rlat's FAISS HNSW, run in the
      open) reaches any target touching ~1% of the corpus.
  7b  a REGIME DIAGNOSTIC for sequences: the mean cosine between successive
      displacements along reading-order chains identifies the local law.
      For i.i.d. passages around a per-document centre it is exactly -1/2;
      for persistent paths it is positive. This corpus measures ~= -1/2:
      documents are CLOUDS, not paths — so momentum extrapolation (the
      path-regime tool, and this demo's original hypothesis) must LOSE to
      centroid prediction (the cloud-regime tool), and does, monotonically
      in the momentum strength. The failed hypothesis is kept on display;
      the diagnostic that replaces it transfers to any band.
  7c  relation types from raw vector pairs: displacements of a rotor-relation
      span that relation's 2-D plane, so the right mining tool is K-PLANES
      (subspace) clustering, not k-means. Planted relations are recovered
      and APPLY to unseen nodes — typed edges that are generated by
      geometry, not stored ("virtual edges"). The same displacement
      clustering finds real structural edge kinds in the corpus without
      labels (weakly at LSA quality; measured, not oversold).
  7d  hierarchy for free: single-linkage components across a threshold sweep
      nest exactly — broader/narrower (SKOS-style) concept levels, every
      concept a set of passages with source receipts.

Corpus: this repository's own docs (real text, LSA stand-in embeddings —
see corpus.py caveat), or a REAL knowledge model when a path is given:

    python3 demo7_latent_graph.py [/path/to/model.rlat]

Requires numpy. Run:  python3 demo7_latent_graph.py
"""

from __future__ import annotations

import heapq
import math
import sys

import numpy as np

from corpus import build_repo_corpus, load_rlat, reading_chains

rng = np.random.default_rng(20260810)
PASSES = []


def check(name, ok, detail=""):
    PASSES.append(bool(ok))
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}{('   (' + detail + ')') if detail else ''}")


def unit_rows(X):
    return X / np.maximum(np.linalg.norm(X, axis=1, keepdims=True), 1e-12)


# ---------------------------------------------------------------- setup ---

if len(sys.argv) > 1:
    corpus = load_rlat(sys.argv[1])
else:
    corpus = build_repo_corpus("/home/user/resonance-lattice")
band, coords = corpus["band"], corpus["coords"]
N, d = band.shape
print(f"corpus: {corpus['label']}")

SIM = band @ band.T
np.fill_diagonal(SIM, -np.inf)

K = 8
knn = np.argsort(-SIM, axis=1)[:, :K]                    # (N, K) neighbour ids

# ------------------------------------------------------------------ 7a ----

print(f"7a. navigability: kNN graph (k={K}), long-range links, search discipline")

parent = list(range(N))


def find(x):
    while parent[x] != x:
        parent[x] = parent[parent[x]]
        x = parent[x]
    return x


for i in range(N):
    for j in knn[i]:
        ri, rj = find(i), find(int(j))
        if ri != rj:
            parent[ri] = rj
comp_sizes = np.bincount([find(i) for i in range(N)])
giant = int(comp_sizes.max())
print(f"    connectivity: largest component {giant}/{N} passages "
      f"({100.0 * giant / N:.1f}%)")

M_LONG = 2
long_links = rng.integers(0, N, size=(N, M_LONG))

# HNSW stores BIDIRECTIONAL links; a directed kNN graph strands nodes that
# are nobody's near neighbour (low in-degree). Build undirected adjacency.
adj = [set() for _ in range(N)]
for i in range(N):
    for j in knn[i]:
        adj[i].add(int(j))
        adj[int(j)].add(i)
    for j in long_links[i]:
        adj[i].add(int(j))
        adj[int(j)].add(i)
adj = [np.array(sorted(s)) for s in adj]


def greedy_route(start, target, nbrs, max_hops=40, beam=1):
    frontier = [(0.0, start)]
    visited = {start}
    for hop in range(1, max_hops + 1):
        cands = []
        for _s, node in frontier:
            for nxt in nbrs(node):
                nxt = int(nxt)
                if nxt == target:
                    return hop
                if nxt not in visited:
                    visited.add(nxt)
                    cands.append((float(band[nxt] @ band[target]), nxt))
        if not cands:
            return None
        cands.sort(reverse=True)
        frontier = cands[:beam]
    return None


def best_first_route(start, target, nbrs, ef=150):
    """HNSW-style search: best-first by similarity-to-target with
    backtracking. Returns nodes expanded, or None if budget exhausted."""
    heap = [(-float(band[start] @ band[target]), start)]
    visited = {start}
    expanded = 0
    while heap and expanded < ef:
        _, node = heapq.heappop(heap)
        expanded += 1
        if node == target:
            return expanded
        for nxt in nbrs(node):
            nxt = int(nxt)
            if nxt not in visited:
                visited.add(nxt)
                heapq.heappush(heap, (-float(band[nxt] @ band[target]), nxt))
    return None


directed = [np.concatenate([knn[i], long_links[i]]) for i in range(N)]
sym_nbrs = lambda v: adj[v]
dir_nbrs = lambda v: directed[v]

trials = 300
stats = {"greedy-directed": [], "greedy": [], "best-first": []}
for _ in range(trials):
    s, t = int(rng.integers(N)), int(rng.integers(N))
    if s == t:
        continue
    stats["greedy-directed"].append(greedy_route(s, t, dir_nbrs, beam=1))
    stats["greedy"].append(greedy_route(s, t, sym_nbrs, beam=1))
    stats["best-first"].append(best_first_route(s, t, sym_nbrs))
sr = {k: 100.0 * sum(x is not None for x in v) / len(v) for k, v in stats.items()}
cost_bf = float(np.mean([x for x in stats["best-first"] if x is not None]))
print(f"    greedy on DIRECTED kNN edges  : {sr['greedy-directed']:5.1f}% reach target")
print(f"    greedy on BIDIRECTIONAL edges : {sr['greedy']:5.1f}% reach target")
print(f"    best-first with backtracking  : {sr['best-first']:5.1f}% reach target, "
      f"touching a mean of {cost_bf:.0f}/{N} nodes ({100 * cost_bf / N:.0f}% of corpus)")
print("    -> similarity says who your neighbours are; it does not say who counts")
print("       YOU as a neighbour. Symmetrising the links is the load-bearing step")
print("       (HNSW does exactly this); backtracking then buys efficiency. Measured")
print("       in the open here — production search stays FAISS (field/ann.py).")
check("kNN graph is essentially one connected component (>= 95%)", giant >= 0.95 * N)
check("edge symmetry is load-bearing: directed greedy fails often, undirected doesn't",
      sr["greedy-directed"] <= sr["greedy"] - 15.0,
      f"{sr['greedy-directed']:.1f}% -> {sr['greedy']:.1f}%")
check("best-first navigation is reliable (>= 99%) while touching <= 15% of corpus",
      sr["best-first"] >= 99.0 and cost_bf <= 0.15 * N,
      f"{sr['best-first']:.1f}%, {100 * cost_bf / N:.0f}%")

# ------------------------------------------------------------------ 7b ----

print("7b. the regime diagnostic: are document chains PATHS or CLOUDS?")

chains = reading_chains(coords)
instances = [(ch[i - 1], ch[i], ch[i + 1])
             for _src, ch in chains for i in range(1, len(ch) - 1)]

# Diagnostic: mean cos between successive displacements delta_k = e_k - e_{k-1}.
# If passages are i.i.d. around a per-document centre (e_i = c + eps_i), the
# shared middle term forces E[cos(delta_k, delta_{k+1})] -> -1/2. A genuine
# path (persistent direction) gives POSITIVE values. This one number selects
# the traversal law, and transfers to any band (run it on a real .rlat).
curv, angles = [], []
for _src, ch in chains:
    for i in range(1, len(ch) - 1):
        d1 = band[ch[i]] - band[ch[i - 1]]
        d2 = band[ch[i + 1]] - band[ch[i]]
        n1, n2 = float(np.linalg.norm(d1)), float(np.linalg.norm(d2))
        if n1 > 1e-9 and n2 > 1e-9:
            curv.append(float(d1 @ d2) / (n1 * n2))
    for a, b in zip(ch, ch[1:]):
        angles.append(math.degrees(math.acos(float(np.clip(band[a] @ band[b], -1, 1)))))
curv = np.array(curv)
sem = float(curv.std() / math.sqrt(len(curv)))
print(f"    {len(instances)} chain steps in {len(chains)} files; median consecutive-passage "
      f"angle {np.median(angles):.0f} deg")
print(f"    chain curvature mean cos(d_k, d_k+1) = {curv.mean():.3f} +- {sem:.3f}")
print(f"    (i.i.d.-cloud signature: -0.500; persistent path: > 0)")
regime_cloud = -0.6 < float(curv.mean()) < -0.35
check("regime detected: documents are clouds, not paths (curvature ~ -1/2)",
      regime_cloud, f"{curv.mean():.3f}")


def rotor_extrapolate(prev, cur, t=1.0):
    """Path-regime tool: continue the geodesic past cur by t x the last angle."""
    w = float(np.clip(prev @ cur, -1.0, 1.0))
    omega = math.acos(w)
    if omega < 1e-9:
        return cur.copy()
    tang = (w * cur - prev) / math.sin(omega)
    return math.cos(t * omega) * cur + math.sin(t * omega) * tang


def norm1(x):
    return x / max(float(np.linalg.norm(x)), 1e-12)


# Cloud regime consequences, testable: (i) directional extrapolation must
# lose, monotonically in strength; (ii) the cloud tool (doc centroid) can
# gate WHICH document but cannot rank members within it; (iii) what wins is
# a TYPED edge (metadata: same-document) gating candidates, plus LOCAL
# similarity ranking within the gate — the residual sequential signal that
# the 0.025 gap between measured curvature and the exact -1/2 promises.
doc_members = {}
for idx, (s, _, _) in enumerate(coords):
    doc_members.setdefault(s, []).append(idx)
doc_members = {s: np.array(v) for s, v in doc_members.items()}

# Each method maps (prev_vec, cur_vec, doc_centroid) -> (ranking vector,
# gated: bool). Gated methods restrict candidates to the current document —
# a TYPED edge from metadata the .rlat registry already stores.
methods = {
    "greedy: similarity to current  ": (lambda p, c, dc: c, False),
    "momentum t=1.0 (path tool)     ": (lambda p, c, dc: rotor_extrapolate(p, c, 1.0), False),
    "momentum t=0.35 (path tool)    ": (lambda p, c, dc: rotor_extrapolate(p, c, 0.35), False),
    "midpoint of last two           ": (lambda p, c, dc: norm1(p + c), False),
    "doc centroid, ungated (cloud)  ": (lambda p, c, dc: dc, False),
    "typed gate (same doc) + greedy ": (lambda p, c, dc: c, True),
    "typed gate + doc centroid      ": (lambda p, c, dc: dc, True),
}

res = {}
for name, (fn, use_gate) in methods.items():
    h1 = h5 = 0
    rr = 0.0
    for a, b, target in instances:
        members = doc_members[coords[b][0]]
        dc = norm1(band[members].mean(axis=0))
        x = fn(band[a], band[b], dc)
        scores = band @ x
        if use_gate:
            mask = np.full(N, -np.inf)
            mask[members] = 0.0
            scores = scores + mask
        scores[[a, b]] = -np.inf
        order = np.argsort(-scores)
        rank = int(np.where(order == target)[0][0]) + 1
        h1 += int(rank == 1)
        h5 += int(rank <= 5)
        rr += 1.0 / rank
    n = len(instances)
    res[name] = (100.0 * h1 / n, 100.0 * h5 / n, rr / n)
print("    next-passage prediction (find k+1 among all passages):")
print("      method                           | hit@1 | hit@5 |  MRR")
for name, (h1, h5, mrr) in res.items():
    print(f"      {name} | {h1:5.1f} | {h5:5.1f} | {mrr:.3f}")

g5 = res["greedy: similarity to current  "][1]
m5 = res["momentum t=1.0 (path tool)     "][1]
m35 = res["momentum t=0.35 (path tool)    "][1]
c5 = res["doc centroid, ungated (cloud)  "][1]
tg5 = res["typed gate (same doc) + greedy "][1]
tc5 = res["typed gate + doc centroid      "][1]
check("momentum harm is monotone in strength (as the cloud regime demands)",
      m5 < m35 < g5, f"{m5:.1f} < {m35:.1f} < {g5:.1f}")
check("cloud tool alone cannot rank within the cloud (centroid far below greedy)",
      c5 < g5, f"{c5:.1f} vs {g5:.1f}")
check("typed metadata edge + local similarity is where traversal wins (>= 1.5x greedy)",
      tg5 >= 1.5 * g5, f"greedy {g5:.1f} -> gated {tg5:.1f}")
check("the local signal is real beyond membership (gated greedy > gated centroid)",
      tg5 > tc5 + 5.0, f"{tg5:.1f} vs {tc5:.1f}")
print("    -> the original hypothesis (momentum beats greedy) FAILED on this band;")
print("       the curvature diagnostic explains why (clouds, not paths) and would")
print("       flip the recommendation wherever it measures > 0. What actually makes")
print("       vectors 'easier to traverse' here: TYPED edges from metadata the .rlat")
print("       already stores (same-document, adjacency), gating a local similarity")
print("       ranking. Run against a production .rlat, this demo re-measures the")
print("       regime and re-scores every method.")

# ------------------------------------------------------------------ 7c ----

print("7c. relation types from raw pairs: k-planes clustering of displacements")

d_s, K_REL, PER = 64, 4, 150
NOISE = 0.03
FEATURE_MASS = 0.35

# Identifiability caveat, discovered by running the fully-random version
# first: a random unit concept in 64d carries only ~sqrt(2/64) ~ 0.18 of its
# mass in any fixed plane, so the rotational displacement (~ 2 sin(th/2) x
# in-plane mass) barely clears the noise floor and cluster purity degrades
# (~84% measured). Relations are recoverable where they act on entities that
# CARRY the relevant feature — modelled here by giving each edge's source
# concept >= FEATURE_MASS in-plane mass. Both numbers are reported.


def make_edges(feature_mass):
    rel_planes, edges, labels = [], [], []
    for r in range(K_REL):
        u = rng.standard_normal(d_s)
        u /= np.linalg.norm(u)
        v = rng.standard_normal(d_s)
        v -= (v @ u) * u
        v /= np.linalg.norm(v)
        th = float(rng.uniform(0.6, 1.2))
        rel_planes.append((u, v, th))
        for _ in range(PER):
            x = rng.standard_normal(d_s)
            x /= np.linalg.norm(x)
            if feature_mass > 0:
                a, b = rng.standard_normal(2)
                inplane = a * u + b * v
                inplane /= np.linalg.norm(inplane)
                x = x + feature_mass * inplane
                x /= np.linalg.norm(x)
            cu, cv = float(x @ u), float(x @ v)
            y = x + cu * ((math.cos(th) - 1) * u + math.sin(th) * v) \
                  + cv * (-math.sin(th) * u + (math.cos(th) - 1) * v)
            y = y + NOISE * rng.standard_normal(d_s)
            y /= np.linalg.norm(y)
            edges.append((x, y))
            labels.append(r)
    return rel_planes, edges, np.array(labels)


rel_planes, edges, labels = make_edges(FEATURE_MASS)
D = unit_rows(np.stack([y - x for x, y in edges]))

# Displacements of ONE rotor-relation fill that rotor's 2-D plane (a great
# circle of directions), so k-means on directions cannot recover relations
# (a first version tried: 57% purity — kept in git history). The right
# object is the SUBSPACE: k-planes clustering — assign each displacement to
# the plane that best contains it, refit planes by SVD, iterate.


def k_planes(D, k, iters=30):
    """k-subspaces clustering with farthest-first seeding: seed each new
    plane from the displacement worst-explained by the planes so far, then
    alternate (assign to best-containing plane / refit plane by SVD).
    Restart selection is by the UNSUPERVISED objective (total contained
    projection mass) — never by labels."""
    n = len(D)
    i0 = int(rng.integers(n))
    u = D[i0].copy()
    v = D[(i0 + 1) % n] - (D[(i0 + 1) % n] @ u) * u
    v /= max(float(np.linalg.norm(v)), 1e-12)
    planes = [(u, v)]
    while len(planes) < k:
        proj = np.stack([(D @ u) ** 2 + (D @ v) ** 2 for u, v in planes], axis=1)
        worst = int(np.argmin(proj.max(axis=1)))
        u = D[worst].copy()
        partner = int(np.argsort(-np.abs(D @ u))[1])
        v = D[partner] - (D[partner] @ u) * u
        v /= max(float(np.linalg.norm(v)), 1e-12)
        planes.append((u, v))
    assign = None
    for _ in range(iters):
        proj = np.stack([(D @ u) ** 2 + (D @ v) ** 2 for u, v in planes], axis=1)
        assign = np.argmax(proj, axis=1)
        for c in range(k):
            m = D[assign == c]
            if len(m) >= 2:
                _, _, Vt = np.linalg.svd(m, full_matrices=False)
                planes[c] = (Vt[0], Vt[1])
    proj = np.stack([(D @ u) ** 2 + (D @ v) ** 2 for u, v in planes], axis=1)
    objective = float(proj.max(axis=1).sum())
    return np.argmax(proj, axis=1), planes, objective


def cluster_purity(D_in, labels_in):
    best_obj, best_assign = -1.0, None
    for _restart in range(10):
        a, p, obj = k_planes(D_in, K_REL)
        if obj > best_obj:
            best_obj, best_assign, best_planes = obj, a, p
    pur = sum(np.bincount(labels_in[best_assign == c], minlength=K_REL).max()
              for c in range(K_REL) if (best_assign == c).any())
    return 100.0 * pur / len(labels_in), best_assign, best_planes


purity, assign, planes = cluster_purity(D, labels)
_, edges0, labels0 = make_edges(0.0)
purity0, _, _ = cluster_purity(unit_rows(np.stack([y - x for x, y in edges0])), labels0)
print(f"    identifiability boundary: purity {purity0:.1f}% on fully-random concepts "
      f"(weak in-plane mass) vs {purity:.1f}% on feature-bearing concepts")
check("k-planes separates planted relations on feature-bearing entities (>= 95%)",
      purity >= 95.0,
      f"purity {purity:.1f}%; selected by unsupervised objective over 10 restarts")

# apply recovered relations to unseen nodes: virtual typed edges
hits, tests = 0, 200
for c in range(K_REL):
    m = labels[assign == c]
    r = int(np.bincount(m, minlength=K_REL).argmax())
    u_hat, v_hat = planes[c]
    u_true, v_true, th_true = rel_planes[r]
    P_err = float(np.linalg.norm(
        np.outer(u_true, u_true) + np.outer(v_true, v_true)
        - np.outer(u_hat, u_hat) - np.outer(v_hat, v_hat), 2))
    ths = []
    for (x, y), a in zip(edges, assign):
        if a == c:
            px = np.array([x @ u_hat, x @ v_hat])
            py = np.array([y @ u_hat, y @ v_hat])
            if np.linalg.norm(px) > 0.05 and np.linalg.norm(py) > 0.05:
                px, py = px / np.linalg.norm(px), py / np.linalg.norm(py)
                ths.append(math.atan2(px[0] * py[1] - px[1] * py[0], float(px @ py)))
    th_hat = float(np.median(ths))
    for _ in range(tests // K_REL):
        x = unit_rows(rng.standard_normal((1, d_s)))[0]

        def apply_rot(u, v, th, x):
            cu, cv = float(x @ u), float(x @ v)
            return x + cu * ((math.cos(th) - 1) * u + math.sin(th) * v) \
                     + cv * (-math.sin(th) * u + (math.cos(th) - 1) * v)

        y_pred = apply_rot(u_hat, v_hat, th_hat, x)
        y_true = apply_rot(u_true, v_true, th_true, x)
        hits += int(float(y_pred @ y_true)
                    / (np.linalg.norm(y_pred) * np.linalg.norm(y_true)) > 0.95)
print(f"    plane recovery error (last relation) {P_err:.3f}; recovered rotors match the")
print(f"    true relation on {hits}/{tests} unseen nodes — typed edges generated, not stored")
check("recovered relations APPLY correctly to unseen nodes (>= 90%)",
      hits >= 0.9 * tests, f"{hits}/{tests}")

# real corpus, same tool, no labels: do displacement clusters align with
# structural edge kinds (adjacent-in-document vs everything else)?
src_of = [s for s, _, _ in coords]
adjacent = set()
for _src, ch in chains:
    for a, b in zip(ch, ch[1:]):
        adjacent.add((a, b))
        adjacent.add((b, a))
edge_list = [(i, int(j)) for i in range(N) for j in knn[i, :4]]
kind = np.array([1 if (i, j) in adjacent else 0 for i, j in edge_list])
D_real = unit_rows(np.stack([band[j] - band[i] for i, j in edge_list]))
assign_r, _, _ = k_planes(D_real, 6)
base_rate = float(kind.mean())
enrich = max((float(kind[assign_r == c].mean()) / max(base_rate, 1e-9))
             for c in range(6) if (assign_r == c).sum() >= 20)
print(f"    real corpus: {len(edge_list)} kNN edges; adjacent-in-document base rate "
      f"{100 * base_rate:.1f}%; max k-planes cluster enrichment {enrich:.2f}x")
check("displacement geometry carries SOME unseen structural signal (>= 1.25x)",
      enrich >= 1.25, f"{enrich:.2f}x — weak at LSA quality; production-band test pre-registered")

# ------------------------------------------------------------------ 7d ----

print("7d. hierarchy for free: single-linkage components across a threshold sweep")

edge_sims = np.array([float(band[i] @ band[j]) for i, j in edge_list])
qs = [float(np.quantile(edge_sims, q)) for q in (0.9, 0.7, 0.5)]


def components(threshold):
    par = list(range(N))

    def f(x):
        while par[x] != x:
            par[x] = par[par[x]]
            x = par[x]
        return x

    for (i, j), s in zip(edge_list, edge_sims):
        if s >= threshold:
            ri, rj = f(i), f(j)
            if ri != rj:
                par[ri] = rj
    return np.array([f(i) for i in range(N)])


levels = [components(t) for t in qs]
nested = all(
    len(np.unique(levels[k + 1][levels[k] == c])) <= 1
    for k in range(len(levels) - 1)
    for c in np.unique(levels[k])
)
for t, lv in zip(qs, levels):
    sizes = np.bincount(lv)
    sizes = sizes[sizes > 0]
    print(f"    threshold {t:.3f}: {len(sizes)} concepts "
          f"(largest {int(sizes.max())}, singletons {int((sizes == 1).sum())})")
check("levels nest exactly (every fine concept sits inside one coarser concept)", nested)
uniq = np.unique(levels[0])
example = uniq[np.argsort(-np.bincount(levels[0])[uniq])][1]
members = np.where(levels[0] == example)[0][:3]
print("    receipt — one fine concept and its passages:")
for m in members:
    s, o, ln = coords[m]
    print(f"      {s}:{o}+{ln}")
print("    -> broader/narrower (SKOS-style) levels from one threshold sweep; every")
print("       concept is a set of passages with exact source receipts. (Production")
print("       variant: complete-linkage, already in field/algebra.py, resists the")
print("       single-linkage chaining visible in the largest coarse concept.)")

print()
print("Summary: yes — a traversable graph is latent in the band, but each layer")
print("needs its OWN mathematics, and two hypotheses died honestly on the way:")
print("connections alone don't give traversal (backtracking does, 7a); momentum")
print("doesn't help where documents are clouds rather than paths — a one-number")
print("curvature diagnostic selects the right traversal law per band (7b);")
print("relations are 2-D planes in displacement space, recoverable by k-planes")
print("(not k-means) and applicable as virtual typed edges (7c); and nested")
print("concept levels with receipts come from a threshold sweep (7d).")
print()
print("ALL PASS" if all(PASSES) else "SOME CHECKS FAILED")
raise SystemExit(0 if all(PASSES) else 1)
