"""Demo 8 — Orbit retrieval: the graph, without storing a graph.

Context: the repository owner reports that earlier graph features were
discarded — no meaningful improvement, add-on rather than core. This demo
takes that verdict as a design constraint: no stored edges, no new query
surface, no sidecar. If corpus structure is to help retrieval, it must live
in the two things the product already IS — the score function and the
coordinates.

The reformulation: **edges are instances; transformations are laws.** Mine
the corpus's recurring displacement structure once at build time as K
relation rotors (k-planes over displacement fields — validated in demo 7),
keep the ~K*(2d+1) floats, and discard every edge. Two retrieval modes fall
out, both running through the existing `scores = band @ q` path:

  orbit-max   score(q, p) = max over the query's ORBIT {q} u {R_c^{+-1} q}
              under the mined rotors — "also search for what this query
              becomes under the corpus's own moves." 2K+1 matvecs; each hit
              is tagged with the rotor that found it (a receipt).

  quotient    a tiny proposition (checked numerically below): averaging over
              the rotation group generated by a mined rotor annihilates its
              plane exactly — so group-invariant retrieval IS flat retrieval
              in a projected band with the mined planes removed. Zero
              query-time overhead; ships as a band variant.

Everything is measured on real text (this repository's own docs; LSA
stand-in embeddings — corpus.py states the caveat), with the negatives
reported as prominently as the positives. Requires numpy.

Run:  python3 demo8_orbit_retrieval.py
"""

from __future__ import annotations

import math
from collections import defaultdict

import numpy as np

from corpus import build_repo_corpus, reading_chains

rng = np.random.default_rng(20260810)
PASSES = []


def check(name, ok, detail=""):
    PASSES.append(bool(ok))
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}{('   (' + detail + ')') if detail else ''}")


def unit_rows(X):
    return X / np.maximum(np.linalg.norm(X, axis=1, keepdims=True), 1e-12)


def norm1(x):
    return x / max(float(np.linalg.norm(x)), 1e-12)


# ------------------------------------------------------------- mining -----

def k_planes(D, k, iters=30, restarts=10):
    """k-subspaces clustering of displacement directions (demo 7's tool);
    restart selection by the unsupervised objective."""
    def one():
        n = len(D)
        i0 = int(rng.integers(n))
        u = D[i0].copy()
        v = D[(i0 + 1) % n] - (D[(i0 + 1) % n] @ u) * u
        v /= max(float(np.linalg.norm(v)), 1e-12)
        planes = [(u, v)]
        while len(planes) < k:
            proj = np.stack([(D @ u) ** 2 + (D @ v) ** 2 for u, v in planes], axis=1)
            worst = int(np.argmin(proj.max(axis=1)))
            u2 = D[worst].copy()
            partner = int(np.argsort(-np.abs(D @ u2))[1])
            v2 = D[partner] - (D[partner] @ u2) * u2
            v2 /= max(float(np.linalg.norm(v2)), 1e-12)
            planes.append((u2, v2))
        assign = None
        for _ in range(iters):
            proj = np.stack([(D @ u) ** 2 + (D @ v) ** 2 for u, v in planes], axis=1)
            assign = np.argmax(proj, axis=1)
            for c in range(k):
                m = D[assign == c]
                if len(m) >= 2:
                    _, _, Vt = np.linalg.svd(m, full_matrices=False)
                    planes[c] = (Vt[0], Vt[1])
        proj = np.stack([(D @ u) ** 2 + (D @ v) ** 2 for u, v in planes], axis=1)
        return np.argmax(proj, axis=1), planes, float(proj.max(axis=1).sum())

    best = max((one() for _ in range(restarts)), key=lambda t: t[2])
    return best[0], best[1]


def mine_rotors(pairs, band, k):
    """Mine K rotor prototypes (plane + angle + support) from raw index pairs.
    The angle is the median in-plane rotation of member edges whose endpoints
    both carry enough in-plane mass (demo 7's identifiability boundary);
    angles are clamped to pi/2 (demo 5's quadrature guardrail)."""
    D = unit_rows(np.stack([band[j] - band[i] for i, j in pairs]))
    assign, planes = k_planes(D, k)
    rotors = []
    for c in range(k):
        members = [p for p, a in zip(pairs, assign) if a == c]
        if len(members) < 10:
            continue
        u, v = planes[c]
        ths = []
        for i, j in members:
            px = np.array([band[i] @ u, band[i] @ v])
            py = np.array([band[j] @ u, band[j] @ v])
            if np.linalg.norm(px) > 0.05 and np.linalg.norm(py) > 0.05:
                px, py = px / np.linalg.norm(px), py / np.linalg.norm(py)
                ths.append(math.atan2(px[0] * py[1] - px[1] * py[0], float(px @ py)))
        if len(ths) < 5:
            continue
        th = float(np.clip(np.median(ths), -math.pi / 2, math.pi / 2))
        rotors.append({"u": u, "v": v, "theta": th, "support": len(members)})
    return rotors


def apply_rotor(x, u, v, theta):
    cu, cv = float(x @ u), float(x @ v)
    c, s = math.cos(theta), math.sin(theta)
    return x + cu * ((c - 1) * u + s * v) + cv * (-s * u + (c - 1) * v)


def orbit(q, rotors):
    """The query's orbit: identity + each mined rotor forward and inverse."""
    out = [("id", q)]
    for r in rotors:
        out.append((f"rot{r['theta']:+.2f}", norm1(apply_rotor(q, r["u"], r["v"], r["theta"]))))
        out.append((f"rot{-r['theta']:+.2f}", norm1(apply_rotor(q, r["u"], r["v"], -r["theta"]))))
    return out


# ------------------------------------------------------------- corpus -----

corpus = build_repo_corpus("/home/user/resonance-lattice")
band, coords = corpus["band"], corpus["coords"]
N, d = band.shape
print(f"corpus: {corpus['label']}")

SIM = band @ band.T
np.fill_diagonal(SIM, -np.inf)
knn4 = np.argsort(-SIM, axis=1)[:, :4]
src_of = [s for s, _, _ in coords]

chains = reading_chains(coords)
files = sorted({s for s, _ in chains})
rng.shuffle(files)
fit_files = set(files[: int(0.6 * len(files))])
adj_pairs_fit, adj_pairs_test = [], []
for s, ch in chains:
    for a, b in zip(ch, ch[1:]):
        (adj_pairs_fit if s in fit_files else adj_pairs_test).append((a, b))
xfile_pairs = [(i, int(j)) for i in range(N) for j in knn4[i] if src_of[i] != src_of[int(j)]]
print(f"    displacement fields: {len(adj_pairs_fit)} fit / {len(adj_pairs_test)} held-out "
      f"reading-adjacency pairs; {len(xfile_pairs)} cross-file kNN pairs")

# ------------------------------------------------------ 8a  the maths -----

print("8a. the quotient proposition: group-averaging == removing the mined planes")
u = norm1(rng.standard_normal(d))
v0 = rng.standard_normal(d)
v = norm1(v0 - (v0 @ u) * u)
m_ord = 5
avg = np.zeros((d, d))
for jj in range(m_ord):
    th = 2 * math.pi * jj / m_ord
    R = np.eye(d) + np.outer(u, u) * (math.cos(th) - 1) + np.outer(v, v) * (math.cos(th) - 1) \
        + (np.outer(v, u) - np.outer(u, v)) * math.sin(th)
    avg += R / m_ord
proj = np.eye(d) - np.outer(u, u) - np.outer(v, v)
check("averaging over the cyclic group C_5 of a rotor == exact plane removal",
      float(np.abs(avg - proj).max()) < 1e-12)
check("...and the result is an orthogonal projection (idempotent)",
      float(np.abs(avg @ avg - avg).max()) < 1e-12)
print("    -> group-invariant retrieval is flat retrieval in a projected band:")
print("       the 'graph' collapses into the coordinates. Zero query-time cost.")

# ------------------------------------------------- 8b  eval A: chains -----

print("8b. eval A — held-out reading-continuation (the hard task from demo 7)")
rotors_adj = mine_rotors(adj_pairs_fit, band, k=4)
print(f"    mined {len(rotors_adj)} adjacency rotors "
      f"(angles {[round(r['theta'], 2) for r in rotors_adj]}, "
      f"support {[r['support'] for r in rotors_adj]})")


def rank_of(scores, target, exclude):
    s = scores.copy()
    s[exclude] = -np.inf
    return int((s > s[target]).sum()) + 1


def eval_pairs(pairs, rotors):
    flat_h5 = orb_h5 = 0
    flat_rr = orb_rr = 0.0
    for a, b in pairs:
        fr = rank_of(band @ band[a], b, [a])
        scores = np.max(np.stack([band @ x for _tag, x in orbit(band[a], rotors)]), axis=0)
        orr = rank_of(scores, b, [a])
        flat_h5 += int(fr <= 5)
        orb_h5 += int(orr <= 5)
        flat_rr += 1.0 / fr
        orb_rr += 1.0 / orr
    n = len(pairs)
    return (100.0 * flat_h5 / n, flat_rr / n), (100.0 * orb_h5 / n, orb_rr / n)


(fa_h5, fa_mrr), (oa_h5, oa_mrr) = eval_pairs(adj_pairs_test, rotors_adj)
print(f"    flat     : hit@5 {fa_h5:5.1f}  MRR {fa_mrr:.3f}")
print(f"    orbit-max: hit@5 {oa_h5:5.1f}  MRR {oa_mrr:.3f}   "
      f"({len(rotors_adj) * 2 + 1} matvecs/query)")

# ------------------------------------------- 8c  eval B: cross-register ---

print("8c. eval B — cross-register retrieval (DESIGN -> VERDICT of the same bench)")
by_dir = defaultdict(lambda: {"design": [], "verdict": []})
for idx, (s, _, _) in enumerate(coords):
    parts = s.split("/")
    if s.startswith("benchmarks/") and len(parts) >= 3:
        name = parts[-1].upper()
        if name.startswith("DESIGN"):
            by_dir["/".join(parts[:-1])]["design"].append(idx)
        elif name.startswith("VERDICT"):
            by_dir["/".join(parts[:-1])]["verdict"].append(idx)
bench_dirs = {k: v for k, v in by_dir.items() if v["design"] and v["verdict"]}
print(f"    {len(bench_dirs)} bench dirs with both DESIGN* and VERDICT* files")

rotors_x = mine_rotors(xfile_pairs, band, k=4)
print(f"    mined {len(rotors_x)} cross-file rotors "
      f"(angles {[round(r['theta'], 2) for r in rotors_x]}, "
      f"support {[r['support'] for r in rotors_x]})")


def quotient_project(X, rotors):
    basis = []
    for r in rotors:
        for w in (r["u"], r["v"]):
            w = w.copy()
            for b_ in basis:
                w -= (w @ b_) * b_
            n = float(np.linalg.norm(w))
            if n > 1e-6:
                basis.append(w / n)
    Y = X.copy()
    for b_ in basis:
        Y = Y - np.outer(Y @ b_, b_)
    return unit_rows(Y) if Y.ndim == 2 else norm1(Y)


med_abs_th = float(np.median([abs(r["theta"]) for r in rotors_x]))
print(f"    mode selector: median |theta| = {med_abs_th:.2f} rad — near-zero angles mean")
print("    the mined planes carry SYMMETRIC spread (nuisance axes), not directed")
print("    moves: the group is ~self-inverse, so its quotient, not its orbit, is")
print("    the right functor on this band.")

band_q = quotient_project(band, rotors_x)

# named-alternative baselines the repo's culture demands:
#   pca-removal  — 'all-but-the-top' style: drop the top-2K GLOBAL principal
#                  components (same number of dims as the quotient removes);
#   random-quot  — drop 2K random directions (targeting control).
mean_vec = band.mean(axis=0)
_, _, Vt_pca = np.linalg.svd(band - mean_vec, full_matrices=False)
n_dims = 2 * len(rotors_x)
band_pca = unit_rows(band - (band @ Vt_pca[:n_dims].T) @ Vt_pca[:n_dims])
R_rand = np.linalg.qr(rng.standard_normal((d, n_dims)))[0].T
band_rand = unit_rows(band - (band @ R_rand.T) @ R_rand)

BANDS = {"flat": band, "quotient": band_q, "pca-removal": band_pca, "random-quot": band_rand}


def eval_cross(mode):
    hits = total = 0
    rr = 0.0
    for _dirname, g in bench_dirs.items():
        targets = set(g["verdict"])
        for q_idx in g["design"]:
            if mode == "orbit":
                scores = np.max(np.stack([band @ x for _t, x in orbit(band[q_idx], rotors_x)]),
                                axis=0)
            else:
                B = BANDS[mode]
                scores = B @ B[q_idx]
            same_file = [i for i in range(N) if src_of[i] == src_of[q_idx]]
            scores[same_file] = -np.inf             # exclude own file entirely
            order = np.argsort(-scores)
            best = next(k for k, idx in enumerate(order) if idx in targets) + 1
            hits += int(best <= 10)
            rr += 1.0 / best
            total += 1
    return 100.0 * hits / total, rr / total


res_cross = {m: eval_cross(m)
             for m in ("flat", "orbit", "quotient", "pca-removal", "random-quot")}
for m, (h10, mrr) in res_cross.items():
    print(f"    {m:11s}: verdict-recall@10 {h10:5.1f}  MRR {mrr:.3f}")

# --------------------------------------------- 8d  regression guard -------

print("8d. regression guard: topical precision must not degrade")
probe = rng.choice(N, 200, replace=False)


def topical_p10(mode):
    tot = 0.0
    for q_idx in probe:
        top_dir = src_of[q_idx].split("/")[0]
        if mode == "orbit":
            scores = np.max(np.stack([band @ x for _t, x in orbit(band[q_idx], rotors_x)]),
                            axis=0)
        else:
            B = BANDS[mode]
            scores = B @ B[q_idx]
        scores[q_idx] = -np.inf
        top = np.argsort(-scores)[:10]
        tot += np.mean([src_of[i].split("/")[0] == top_dir for i in top])
    return 100.0 * tot / len(probe)


guard = {m: topical_p10(m)
         for m in ("flat", "orbit", "quotient", "pca-removal", "random-quot")}
print("    same-top-level-dir precision@10: "
      + " | ".join(f"{m} {v:.1f}" for m, v in guard.items()))

# ----------------------------------------------------------- verdicts -----

print()
print("Measured verdicts (set after running, stated as findings, not hypotheses):")
check("quotient proposition holds exactly (the graph can live in the coordinates)",
      PASSES[0] and PASSES[1])
check("orbit-max does NOT rescue reading-continuation (cloud regime, as demo 7 said)",
      oa_h5 <= fa_h5 + 2.0, f"flat {fa_h5:.1f} vs orbit {oa_h5:.1f}")
cr_f, cr_o, cr_q = res_cross["flat"][0], res_cross["orbit"][0], res_cross["quotient"][0]
cr_p, cr_r = res_cross["pca-removal"][0], res_cross["random-quot"][0]
check("cross-register: at least one edge-free mode beats flat recall@10 by >= 5 points",
      max(cr_o, cr_q) >= cr_f + 5.0, f"flat {cr_f:.1f} -> orbit {cr_o:.1f} / quotient {cr_q:.1f}")
check("targeting matters: removing random directions does not reproduce the gain",
      cr_r <= cr_f + 2.0, f"random-quot {cr_r:.1f} vs flat {cr_f:.1f}")
print(f"    displacement-mined quotient vs global-PCA removal ('all-but-the-top'): "
      f"{cr_q:.1f} vs {cr_p:.1f} — "
      + ("the mining is load-bearing" if cr_q > cr_p + 2.0
         else "PCA matches here; the claim shrinks to the group framing + receipts"
         if abs(cr_q - cr_p) <= 2.0 else "PCA ahead here; mining not load-bearing on this band"))
check("guard: the winning mode costs <= 5 points of topical precision",
      (guard["orbit" if cr_o >= cr_q else "quotient"] >= guard["flat"] - 5.0))

print()
print("Summary: no edges were stored and no query surface was added. The corpus's")
print("recurring transformations, mined once, either transport the query (orbit-max,")
print("2K+1 matvecs, per-hit receipts) or vanish into the coordinates (quotient")
print("band, zero overhead). Where demo 7's diagnostic says there is no directional")
print("signal (reading order), orbit honestly buys nothing — the win to check on a")
print("production band is cross-register recall, pre-registered in")
print("ORBIT_RETRIEVAL.md with kill criteria.")
print()
print("ALL PASS" if all(PASSES) else "SOME CHECKS FAILED")
raise SystemExit(0 if all(PASSES) else 1)
